# -*- coding: utf-8 -*-
"""google playstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_EZiZWtmY5vJm-mQHQQqrw71Y5FTS620
"""

!pip install numpy
import numpy as np
!pip install pandas
import pandas as pd
!pip install seaborn
import seaborn as sns
!pip install matplotlib
import matplotlib.pyplot as plt

gpd=pd.read_csv("/content/googleplaystore.csv")

gpd.head(1)

gpd.info()

gpd.shape

gpd.describe()

sns.heatmap(gpd.isnull(),yticklabels=False,cbar=False,cmap="tab20c_r")
plt.title("Missing data")
plt.show()

gpd.dropna(inplace=True)

sns.heatmap(gpd.isnull(),yticklabels=False,cbar=False,cmap="tab20c_r")
plt.title("Missing data")
plt.show()

dgpd=gpd[gpd.duplicated()]
print("Numbers of duplicated rows:",dgpd.shape)

fgpd=gpd.drop_duplicates()

fgpd.shape

plt.figure(figsize=(60,5))
sns.countplot(x=fgpd["Category"])
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(x=fgpd["Type"])
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(x=fgpd["Content Rating"])
plt.show()

plt.figure(figsize=(45,5))
sns.countplot(x=fgpd["Android Ver"])
plt.show()

plt.figure(figsize=(30,15))
sns.countplot(x="Installs",hue="Category",data=fgpd)
plt.show()